package sk.tuke.gamestudio.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01
 * Generated source version: 2.2
 */
@WebService (name = "ScoreWebService", targetNamespace = "http://webservice.gamestudio.tuke.sk/")
@XmlSeeAlso ({
	ObjectFactory.class
})
public interface ScoreWebService
{


	/**
	 * @param arg0
	 * @return returns boolean
	 *
	 * @throws ScoreException_Exception
	 */
	@WebMethod
	@WebResult (targetNamespace = "")
	@RequestWrapper (localName = "addScore", targetNamespace = "http://webservice.gamestudio.tuke.sk/", className = "sk.tuke.gamestudio.webservice.AddScore")
	@ResponseWrapper (localName = "addScoreResponse", targetNamespace = "http://webservice.gamestudio.tuke.sk/", className = "sk.tuke.gamestudio.webservice.AddScoreResponse")
	@Action (input = "http://webservice.gamestudio.tuke.sk/ScoreWebService/addScoreRequest", output = "http://webservice.gamestudio.tuke.sk/ScoreWebService/addScoreResponse", fault = {
		@FaultAction (className = ScoreException_Exception.class, value = "http://webservice.gamestudio.tuke.sk/ScoreWebService/addScore/Fault/ScoreException")
	})
	public boolean addScore(
		@WebParam (name = "arg0", targetNamespace = "")
			Score arg0)
		throws ScoreException_Exception
	;

	/**
	 * @param arg0
	 * @return returns java.util.List<sk.tuke.gamestudio.webservice.Score>
	 *
	 * @throws ScoreException_Exception
	 */
	@WebMethod
	@WebResult (targetNamespace = "")
	@RequestWrapper (localName = "getBestScoresForGame", targetNamespace = "http://webservice.gamestudio.tuke.sk/", className = "sk.tuke.gamestudio.webservice.GetBestScoresForGame")
	@ResponseWrapper (localName = "getBestScoresForGameResponse", targetNamespace = "http://webservice.gamestudio.tuke.sk/", className = "sk.tuke.gamestudio.webservice.GetBestScoresForGameResponse")
	@Action (input = "http://webservice.gamestudio.tuke.sk/ScoreWebService/getBestScoresForGameRequest", output = "http://webservice.gamestudio.tuke.sk/ScoreWebService/getBestScoresForGameResponse", fault = {
		@FaultAction (className = ScoreException_Exception.class, value = "http://webservice.gamestudio.tuke.sk/ScoreWebService/getBestScoresForGame/Fault/ScoreException")
	})
	public List<Score> getBestScoresForGame(
		@WebParam (name = "arg0", targetNamespace = "")
			String arg0)
		throws ScoreException_Exception
	;

}
