
package sk.tuke.gamestudio.webservice.favorites;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FavoriteGameService", targetNamespace = "http://favorites.webservice.gamestudio.tuke.sk/", wsdlLocation = "http://localhost:8080/gamestudio_server/FavoriteGameService?WSDL")
public class FavoriteGameService
    extends Service
{

    private final static URL FAVORITEGAMESERVICE_WSDL_LOCATION;
    private final static WebServiceException FAVORITEGAMESERVICE_EXCEPTION;
    private final static QName FAVORITEGAMESERVICE_QNAME = new QName("http://favorites.webservice.gamestudio.tuke.sk/", "FavoriteGameService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/gamestudio_server/FavoriteGameService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FAVORITEGAMESERVICE_WSDL_LOCATION = url;
        FAVORITEGAMESERVICE_EXCEPTION = e;
    }

    public FavoriteGameService() {
        super(__getWsdlLocation(), FAVORITEGAMESERVICE_QNAME);
    }

    public FavoriteGameService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FAVORITEGAMESERVICE_QNAME, features);
    }

    public FavoriteGameService(URL wsdlLocation) {
        super(wsdlLocation, FAVORITEGAMESERVICE_QNAME);
    }

    public FavoriteGameService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FAVORITEGAMESERVICE_QNAME, features);
    }

    public FavoriteGameService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FavoriteGameService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FavoriteGameWebService
     */
    @WebEndpoint(name = "FavoriteGameServicePort")
    public FavoriteGameWebService getFavoriteGameServicePort() {
        return super.getPort(new QName("http://favorites.webservice.gamestudio.tuke.sk/", "FavoriteGameServicePort"), FavoriteGameWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FavoriteGameWebService
     */
    @WebEndpoint(name = "FavoriteGameServicePort")
    public FavoriteGameWebService getFavoriteGameServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://favorites.webservice.gamestudio.tuke.sk/", "FavoriteGameServicePort"), FavoriteGameWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FAVORITEGAMESERVICE_EXCEPTION!= null) {
            throw FAVORITEGAMESERVICE_EXCEPTION;
        }
        return FAVORITEGAMESERVICE_WSDL_LOCATION;
    }

}
