
package sk.tuke.gamestudio.webservice.favorites;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FavoriteGameWebService", targetNamespace = "http://favorites.webservice.gamestudio.tuke.sk/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FavoriteGameWebService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @throws FavoriteException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "removeFavorite", targetNamespace = "http://favorites.webservice.gamestudio.tuke.sk/", className = "sk.tuke.gamestudio.webservice.favorites.RemoveFavorite")
    @ResponseWrapper(localName = "removeFavoriteResponse", targetNamespace = "http://favorites.webservice.gamestudio.tuke.sk/", className = "sk.tuke.gamestudio.webservice.favorites.RemoveFavoriteResponse")
    @Action(input = "http://favorites.webservice.gamestudio.tuke.sk/FavoriteGameWebService/removeFavoriteRequest", output = "http://favorites.webservice.gamestudio.tuke.sk/FavoriteGameWebService/removeFavoriteResponse", fault = {
        @FaultAction(className = FavoriteException_Exception.class, value = "http://favorites.webservice.gamestudio.tuke.sk/FavoriteGameWebService/removeFavorite/Fault/FavoriteException")
    })
    public void removeFavorite(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Game arg1)
        throws FavoriteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<sk.tuke.gamestudio.webservice.favorites.FavoriteGameEntity>
     * @throws FavoriteException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFavorites", targetNamespace = "http://favorites.webservice.gamestudio.tuke.sk/", className = "sk.tuke.gamestudio.webservice.favorites.GetFavorites")
    @ResponseWrapper(localName = "getFavoritesResponse", targetNamespace = "http://favorites.webservice.gamestudio.tuke.sk/", className = "sk.tuke.gamestudio.webservice.favorites.GetFavoritesResponse")
    @Action(input = "http://favorites.webservice.gamestudio.tuke.sk/FavoriteGameWebService/getFavoritesRequest", output = "http://favorites.webservice.gamestudio.tuke.sk/FavoriteGameWebService/getFavoritesResponse", fault = {
        @FaultAction(className = FavoriteException_Exception.class, value = "http://favorites.webservice.gamestudio.tuke.sk/FavoriteGameWebService/getFavorites/Fault/FavoriteException")
    })
    public List<FavoriteGameEntity> getFavorites(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws FavoriteException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws FavoriteException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "addFavorite2", targetNamespace = "http://favorites.webservice.gamestudio.tuke.sk/", className = "sk.tuke.gamestudio.webservice.favorites.AddFavorite2")
    @ResponseWrapper(localName = "addFavorite2Response", targetNamespace = "http://favorites.webservice.gamestudio.tuke.sk/", className = "sk.tuke.gamestudio.webservice.favorites.AddFavorite2Response")
    @Action(input = "http://favorites.webservice.gamestudio.tuke.sk/FavoriteGameWebService/addFavorite2Request", output = "http://favorites.webservice.gamestudio.tuke.sk/FavoriteGameWebService/addFavorite2Response", fault = {
        @FaultAction(className = FavoriteException_Exception.class, value = "http://favorites.webservice.gamestudio.tuke.sk/FavoriteGameWebService/addFavorite2/Fault/FavoriteException")
    })
    public void addFavorite2(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Game arg1)
        throws FavoriteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws FavoriteException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "addFavorite1", targetNamespace = "http://favorites.webservice.gamestudio.tuke.sk/", className = "sk.tuke.gamestudio.webservice.favorites.AddFavorite1")
    @ResponseWrapper(localName = "addFavorite1Response", targetNamespace = "http://favorites.webservice.gamestudio.tuke.sk/", className = "sk.tuke.gamestudio.webservice.favorites.AddFavorite1Response")
    @Action(input = "http://favorites.webservice.gamestudio.tuke.sk/FavoriteGameWebService/addFavorite1Request", output = "http://favorites.webservice.gamestudio.tuke.sk/FavoriteGameWebService/addFavorite1Response", fault = {
        @FaultAction(className = FavoriteException_Exception.class, value = "http://favorites.webservice.gamestudio.tuke.sk/FavoriteGameWebService/addFavorite1/Fault/FavoriteException")
    })
    public void addFavorite1(
        @WebParam(name = "arg0", targetNamespace = "")
        FavoriteGameEntity arg0)
        throws FavoriteException_Exception
    ;

}
