
package sk.tuke.gamestudio.webservice.favorites;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "FavoriteException", targetNamespace = "http://favorites.webservice.gamestudio.tuke.sk/")
public class FavoriteException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FavoriteException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public FavoriteException_Exception(String message, FavoriteException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public FavoriteException_Exception(String message, FavoriteException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: sk.tuke.gamestudio.webservice.favorites.FavoriteException
     */
    public FavoriteException getFaultInfo() {
        return faultInfo;
    }

}
